/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaSwingPortfolio;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author wahidsadik
 */
public class MainPage extends javax.swing.JFrame {

	/**
	 * Creates new form MainPage
	 */
//	CardLayout cardLayout;
	public MainPage() {
		initComponents();
//		cardLayout = (CardLayout) (right_p.getLayout());
		setResizable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                left_p = new javax.swing.JPanel();
                btn1 = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                btn2 = new javax.swing.JButton();
                btn3 = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                btn4 = new javax.swing.JButton();
                right_p = new javax.swing.JPanel();
                right_p1 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel19 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jLabel20 = new javax.swing.JLabel();
                jLabel16 = new javax.swing.JLabel();
                jLabel21 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                jLabel22 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                left_p.setBackground(new java.awt.Color(39, 39, 39));

                btn1.setBackground(new java.awt.Color(255, 255, 255));
                btn1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                btn1.setForeground(new java.awt.Color(240, 240, 240));
                btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/static_gray.png"))); // NOI18N
                btn1.setText("ABOUT ME");
                btn1.setBorder(null);
                btn1.setBorderPainted(false);
                btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btn1.setFocusPainted(false);
                btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btn1.setMinimumSize(new java.awt.Dimension(56, 17));
                btn1.setPreferredSize(new java.awt.Dimension(56, 17));
                btn1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn1ActionPerformed(evt);
                        }
                });

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/me.png"))); // NOI18N

                btn2.setBackground(new java.awt.Color(255, 255, 255));
                btn2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                btn2.setForeground(new java.awt.Color(240, 240, 240));
                btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/static_gray.png"))); // NOI18N
                btn2.setText("DOWNLOAD CV");
                btn2.setBorder(null);
                btn2.setBorderPainted(false);
                btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btn2.setFocusPainted(false);
                btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btn2.setMinimumSize(new java.awt.Dimension(56, 17));
                btn2.setPreferredSize(new java.awt.Dimension(56, 17));
                btn2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn2ActionPerformed(evt);
                        }
                });

                btn3.setBackground(new java.awt.Color(255, 255, 255));
                btn3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                btn3.setForeground(new java.awt.Color(240, 240, 240));
                btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/static_gray.png"))); // NOI18N
                btn3.setText("GITHUB");
                btn3.setBorder(null);
                btn3.setBorderPainted(false);
                btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btn3.setFocusPainted(false);
                btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btn3.setMinimumSize(new java.awt.Dimension(56, 17));
                btn3.setPreferredSize(new java.awt.Dimension(56, 17));
                btn3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn3ActionPerformed(evt);
                        }
                });

                jLabel4.setBackground(new java.awt.Color(153, 153, 153));
                jLabel4.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(204, 204, 204));
                jLabel4.setText("© 2023, WAHID SADIK");

                btn4.setBackground(new java.awt.Color(255, 255, 255));
                btn4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                btn4.setForeground(new java.awt.Color(240, 240, 240));
                btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/static_gray.png"))); // NOI18N
                btn4.setText("CONTACT ME");
                btn4.setBorder(null);
                btn4.setBorderPainted(false);
                btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btn4.setFocusPainted(false);
                btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btn4.setMinimumSize(new java.awt.Dimension(56, 17));
                btn4.setPreferredSize(new java.awt.Dimension(56, 17));
                btn4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn4ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout left_pLayout = new javax.swing.GroupLayout(left_p);
                left_p.setLayout(left_pLayout);
                left_pLayout.setHorizontalGroup(
                        left_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_pLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                        .addGroup(left_pLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                );
                left_pLayout.setVerticalGroup(
                        left_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(left_pLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addContainerGap())
                );

                right_p.setBackground(new java.awt.Color(240, 240, 240));
                right_p.setLayout(new java.awt.CardLayout());

                right_p1.setBackground(new java.awt.Color(240, 240, 240));
                right_p1.setForeground(new java.awt.Color(0, 0, 0));

                jLabel5.setFont(new java.awt.Font("Verdana", 0, 32)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(78, 154, 6));
                jLabel5.setText("_HELLO WORLD!");

                jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(78, 154, 6));
                jLabel8.setText("I AM WAHID SADIK");

                jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(153, 153, 153));
                jLabel9.setText("TECH ENTHUSIAST, COMPUTER SCIENCE STUDENT");

                jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(153, 153, 153));
                jLabel10.setText("Skillset");

                jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(153, 153, 153));
                jLabel11.setText("Problem Solving _");

                jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel14.setForeground(new java.awt.Color(153, 153, 153));
                jLabel14.setText("Proficient in C and C++, with experience solving 400+ problems on online judges");

                jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(153, 153, 153));
                jLabel12.setText("Data Structure and Algorithm  _");

                jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel18.setForeground(new java.awt.Color(153, 153, 153));
                jLabel18.setText("Solid understanding of data structures and algorithms, enhancing problem-solving.");

                jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel13.setForeground(new java.awt.Color(153, 153, 153));
                jLabel13.setText("Object-Oriented Programming  _");

                jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel19.setForeground(new java.awt.Color(153, 153, 153));
                jLabel19.setText("Proficient in Java, experienced in creating GUI-based applications and basic games.");

                jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel15.setForeground(new java.awt.Color(153, 153, 153));
                jLabel15.setText("Web Development _");

                jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel20.setForeground(new java.awt.Color(153, 153, 153));
                jLabel20.setText("Learning HTML, CSS, Tailwind CSS, JavaScript, React, Firebase, and Node.js.");

                jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel16.setForeground(new java.awt.Color(153, 153, 153));
                jLabel16.setText("UI/UX Design _");

                jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel21.setForeground(new java.awt.Color(153, 153, 153));
                jLabel21.setText("Proficient in creating Android app prototypes using Figma.");

                jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel17.setForeground(new java.awt.Color(153, 153, 153));
                jLabel17.setText("Other _");

                jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                jLabel22.setForeground(new java.awt.Color(153, 153, 153));
                jLabel22.setText("Proficient in Python, with some project experience, and skilled in document management");

                jPanel1.setLayout(new java.awt.GridBagLayout());

                jLabel1.setBackground(new java.awt.Color(51, 51, 51));
                jLabel1.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(51, 51, 51));
                jLabel1.setText("I'm a passionate newbie programmer with a curious mind, eager to explore various coding aspects");

                jLabel2.setBackground(new java.awt.Color(51, 51, 51));
                jLabel2.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(51, 51, 51));
                jLabel2.setText("and expand my knowledge and skills. I also have a strong dedication to completing projects");

                jLabel6.setBackground(new java.awt.Color(51, 51, 51));
                jLabel6.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(51, 51, 51));
                jLabel6.setText("with utmost commitment. Currently, I'm focused on Web Development.");

                javax.swing.GroupLayout right_p1Layout = new javax.swing.GroupLayout(right_p1);
                right_p1.setLayout(right_p1Layout);
                right_p1Layout.setHorizontalGroup(
                        right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(right_p1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel2)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addGroup(right_p1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22))
                                        .addGroup(right_p1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21))
                                        .addGroup(right_p1Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20))
                                        .addGroup(right_p1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19))
                                        .addGroup(right_p1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel18))
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel8)
                                        .addGroup(right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, right_p1Layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel14))))
                                .addGap(0, 59, Short.MAX_VALUE))
                );
                right_p1Layout.setVerticalGroup(
                        right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(right_p1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(42, 42, 42)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(right_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel17))
                                .addGap(69, 69, 69))
                );

                right_p.add(right_p1, "right_p1");
                right_p1.getAccessibleContext().setAccessibleName("right_p1");
                right_p1.getAccessibleContext().setAccessibleParent(right_p1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(left_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(right_p, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(right_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(left_p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
		// TODO add your handling code here:
		// cardLayout.show(right_p, "right_p1");
        }//GEN-LAST:event_btn1ActionPerformed

        private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
		// TODO add your handling code here:
//		cardLayout.show(right_p, "right_p2");
		try {
			Desktop.getDesktop().browse(new URL("https://drive.google.com/file/d/1TVlWNJGG84VHGfp-ZZr9N8KEJZqskZH3/view?usp=sharing").toURI());
		} catch (IOException | URISyntaxException e) {
		}
        }//GEN-LAST:event_btn2ActionPerformed

        private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
		// TODO add your handling code here:
//		cardLayout.show(right_p, "right_p3");
		try {
			Desktop.getDesktop().browse(new URL("https://github.com/wahidsadikjishan").toURI());
		} catch (Exception e) {
			e.printStackTrace();
		}
        }//GEN-LAST:event_btn3ActionPerformed

        private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
		// TODO add your handling code here:
		try {
			Desktop.getDesktop().browse(new URL("mailto:wahidsadikjishan@gmail.com").toURI());
		} catch (Exception e) {
			e.printStackTrace();
		}
        }//GEN-LAST:event_btn4ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainPage().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn1;
        private javax.swing.JButton btn2;
        private javax.swing.JButton btn3;
        private javax.swing.JButton btn4;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel left_p;
        private javax.swing.JPanel right_p;
        private javax.swing.JPanel right_p1;
        // End of variables declaration//GEN-END:variables
}
